name: Code Generation Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  codegen-check:
    name: Verify Code Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.62.2

      - name: Run code generation
        run: |
          # fetch submodule tags since actions/checkout does not
          git submodule foreach 'git fetch --unshallow || true'
          # Run all code generation steps
          pixi run codegen

      - name: Check for uncommitted changes
        run: |
          pixi run check-codegen
          bash ./check_codegen.sh
